// data/src/components/HKInfo.vue
<template>
  <div class="w-full max-w-4xl space-y-6 py-6">
    <!-- HomeKey Info Card -->
    <div v-if="loading" class="text-center">
      <span class="loading loading-spinner loading-lg"></span>
    </div>
    <div v-else-if="error" class="text-center text-error">
      <p>Error: {{ error }}</p>
    </div>
    <div v-else class="card bg-base-200 shadow-xl">
      <h2 class="card-title p-4 pb-0"><div class="badge badge-info badge-md">Info</div> HomeKey</h2>
      <div class="card-body p-4">
        <div>
          <div class="stats stats-vertical md:stats-horizontal shadow bg-base-100 w-full">
            <div class="stat">
              <div class="stat-title">Reader GID</div>
              <div class="stat-value text-xl">{{ hkInfo.group_identifier || 'N/A' }}</div>
            </div>
            <div class="stat">
              <div class="stat-title">Reader ID</div>
              <div class="stat-value text-xl">{{ hkInfo.unique_identifier || 'N/A' }}</div>
            </div>
            <div class="stat">
              <div class="stat-title">Issuers</div>
              <div class="stat-value text-xl">{{ hkInfo.issuers ? hkInfo.issuers.length : 0 }}</div>
            </div>
          </div>

          <div v-if="hkInfo.issuers && hkInfo.issuers.length > 0" class="mt-8">
            <div v-for="(issuer, index) in hkInfo.issuers" :key="`issuer-${index}`" class="list-row">
              <div class="collapse collapse-arrow bg-base-100 shadow">
                <input type="checkbox" name="info-collapse" />
                <div class="collapse-title font-semibold">
                  <div class="text-xs uppercase font-semibold opacity-60">Issuer</div>
                  {{ issuer.issuerId || 'N/A' }}
                </div>
                <div class="collapse-content text-sm">
                  <ul v-if="issuer.endpoints && issuer.endpoints.length > 0" class="ml-4">
                    <li v-for="(endpoint, epIndex) in issuer.endpoints" :key="`ep-${epIndex}`">
                      <div class="text-xs uppercase font-semibold opacity-60">Endpoint Id:</div>
                      {{ endpoint.endpointId || 'N/A' }}
                      <div v-if="epIndex < issuer.endpoints.length - 1" class="divider my-2 "></div>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="card bg-base-200 shadow-xl">
      <h2 class="card-title p-4 pb-0"><div class="badge badge-info badge-md">Info</div> System</h2>
      <div class="card-body p-4">
        <div class="flex flex-col gap-4">
          <div class="stats stats-vertical md:stats-horizontal shadow bg-base-100 w-full">
            <div class="stat">
              <div class="stat-title">Device Name</div>
              <div class="stat-value text-xl">{{ sysInfo?.deviceName || 'N/A' }}</div>
            </div>
            <div class="stat">
              <div class="stat-title">Version</div>
              <div class="stat-value text-xl">{{ sysInfo?.version || 'N/A' }}</div>
            </div>
            <div class="stat">
              <div class="stat-title">Uptime</div>
              <div class="stat-value text-xl">{{ sysInfo?.uptime || 'N/A' }}</div>
            </div>
          </div>
          <div class="stats stats-vertical md:stats-horizontal shadow bg-base-100 w-full">
            <div class="stat">
              <div class="stat-title">WiFi SSID</div>
              <div class="stat-value text-xl">{{ sysInfo?.wifi_ssid || 'N/A' }}</div>
            </div>
            <div v-if="!sysInfo?.eth_enabled" class="stat">
              <div class="stat-title">WiFi RSSI</div>
              <div class="stat-value text-xl">{{ sysInfo?.wifi_rssi || 'N/A' }} ({{ wifi_signal }})</div>
            </div>
            <div class="stat">
              <div class="stat-title">Ethernet enabled</div>
              <div class="stat-value text-xl">{{ sysInfo?.eth_enabled ? 'Yes' : 'No' }}</div>
            </div>
          </div>
        </div>
      </div>
    </div>
    
    <!-- WebSocket Test Component -->
    <WebSocketTestComponent v-if="dev" />
  </div>
</template>

<script>
import { fetchConfig } from '../services/api';
import { defineAsyncComponent } from 'vue';

export default {
  inject: ['sysInfo'],
  data() {
    return {
      wifi_signal: "Unknown",
      hkInfo: {},
      loading: true,
      error: null,
      dev: __DEV__
    };
  },
  async mounted() {
    try {
      this.hkInfo = await fetchConfig('hkinfo');
    } catch (e) {
      this.error = e.message;
    } finally {
      this.loading = false;
      }
  },
  components: {
    WebSocketTestComponent : __DEV__ ? defineAsyncComponent(() => import('./WebSocketTest.vue')) : null,
  },
  watch: {
    'sysInfo.wifi_rssi': {
      handler(wifi_rssi) {
        if(wifi_rssi <= -30 || wifi_rssi >= -70) {
          this.wifi_signal = 'Excellent';
        } else if (wifi_rssi <= -71 || wifi_rssi >= -80) {
          this.wifi_signal = 'Good';
        } else if (wifi_rssi <= -81 || wifi_rssi >= -90) {
          this.wifi_signal = 'Fair';
        } else if (wifi_rssi <= -91 || wifi_rssi >= -100) {
          this.wifi_signal = 'Poor';
        } else {
          this.wifi_signal = 'Unknown';
        }
      }
    }
  }
};
</script>

// data/src/lib/components/HKInfo.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import type { HKInfo } from "$lib/types/api.js";
  import { systemInfo } from "$lib/stores/system.svelte.js";
  import {
    loadingStates,
    setLoadingState,
  } from "$lib/stores/loading.svelte.js";
  import { calculateWifiSignal } from "$lib/utils/wifi.js";
  const version : string = __DEV__ ? 'dev' : __VERSION__;

  /**
   * Props for HKInfo component
   * @type {HKInfo | null} hkInfo - HomeKey information data
   * @type {string | null} error - Error message if data loading failed
   */
  let { hkInfo, error }: { hkInfo: HKInfo | null; error: string | null } =
    $props();

  onMount(async (): Promise<void> => {
    systemInfo.uptime == 0 && setLoadingState("systemInfoLoading", true);
  });

  let wifi_rssi = $derived(systemInfo?.wifi_rssi);
  let wifi_signal = $derived.by(() => calculateWifiSignal(wifi_rssi));
</script>

<div class="w-full py-6 flex flex-col items-center">
  <div class="flex flex-col max-w-4xl gap-6">
    <!-- HomeKey Info Card -->
    {#if loadingStates.hkInfoLoading}
      <div
        class="card bg-base-200 shadow-xl"
        aria-live="polite"
        aria-label="Loading HomeKey information"
      >
        <h2 class="card-title p-4 pb-0">
          <div
            class="badge badge-info badge-md"
            aria-label="HomeKey information section"
          >
            Info
          </div>
          HomeKey
        </h2>
        <div class="card-body p-4">
          <div class="flex justify-center">
            <span
              class="loading loading-spinner loading-lg"
              aria-label="Loading HomeKey data"
            ></span>
          </div>
        </div>
      </div>
    {:else if error}
      <div class="text-center text-error" aria-live="assertive">
        <p>Error: {error}</p>
      </div>
    {:else if hkInfo}
      <div class="card bg-base-200 shadow-xl">
        <h2 class="card-title p-4 pb-0">
          <div class="badge badge-info badge-md">Info</div>
          HomeKey
        </h2>
        <div class="card-body p-4">
          <div>
            <div
              class="stats stats-vertical md:stats-horizontal shadow bg-base-100 w-full"
            >
              <div class="stat">
                <div class="stat-title">Reader GID</div>
                <div class="stat-value text-xl">
                  {hkInfo.group_identifier || "N/A"}
                </div>
              </div>
              <div class="stat">
                <div class="stat-title">Reader ID</div>
                <div class="stat-value text-xl">
                  {hkInfo.unique_identifier || "N/A"}
                </div>
              </div>
              <div class="stat">
                <div class="stat-title">Issuers</div>
                <div class="stat-value text-xl">
                  {hkInfo.issuers ? hkInfo.issuers.length : 0}
                </div>
              </div>
            </div>

            {#if hkInfo.issuers && hkInfo.issuers.length > 0}
              <div class="mt-8 space-y-2">
                {#each hkInfo.issuers as issuer, index (`issuer-${index}`)}
                  <div class="list-row">
                    <div class="collapse collapse-arrow bg-base-100 shadow">
                      <input type="checkbox" name="info-collapse" />
                      <div class="collapse-title font-semibold">
                        <div class="text-xs uppercase font-semibold opacity-60">
                          Issuer
                        </div>
                        {issuer.issuerId || "N/A"}
                      </div>
                      <div class="collapse-content text-sm">
                        {#if issuer.endpoints && issuer.endpoints.length > 0}
                          <ul class="ml-4">
                            {#each issuer.endpoints as endpoint, epIndex (`ep-${epIndex}`)}
                              <li>
                                <div
                                  class="text-xs uppercase font-semibold opacity-60"
                                >
                                  Endpoint Id:
                                </div>
                                {endpoint.endpointId || "N/A"}
                                {#if epIndex < issuer.endpoints.length - 1}
                                  <div class="divider my-2"></div>
                                {/if}
                              </li>
                            {/each}
                          </ul>
                        {/if}
                      </div>
                    </div>
                  </div>
                {/each}
              </div>
            {/if}
          </div>
        </div>
      </div>
    {/if}

    <div
      class="card bg-base-200 shadow-xl"
      aria-live="polite"
      aria-label="System information"
    >
      <h2 class="card-title p-4 pb-0">
        <div
          class="badge badge-info badge-md"
          aria-label="System information section"
        >
          Info
        </div>
        System
      </h2>
      <div class="card-body p-4">
        {#if loadingStates.systemInfoLoading}
          <div
            class="flex flex-col gap-4"
            aria-label="Loading system information"
          >
            <div
              class="stats stats-vertical md:stats-horizontal shadow bg-base-100 w-full"
            >
              <div class="stat">
                <div class="skeleton h-4 w-20 mb-2"></div>
                <div class="skeleton h-6 w-32"></div>
              </div>
              <div class="stat">
                <div class="skeleton h-4 w-16 mb-2"></div>
                <div class="skeleton h-6 w-24"></div>
              </div>
              <div class="stat">
                <div class="skeleton h-4 w-14 mb-2"></div>
                <div class="skeleton h-6 w-28"></div>
              </div>
            </div>
            <div
              class="stats stats-vertical md:stats-horizontal shadow bg-base-100 w-full"
            >
              <div class="stat">
                <div class="skeleton h-4 w-18 mb-2"></div>
                <div class="skeleton h-6 w-36"></div>
              </div>
              <div class="stat">
                <div class="skeleton h-4 w-16 mb-2"></div>
                <div class="skeleton h-6 w-40"></div>
              </div>
              <div class="stat">
                <div class="skeleton h-4 w-24 mb-2"></div>
                <div class="skeleton h-6 w-12"></div>
              </div>
            </div>
          </div>
        {:else}
          <div class="flex flex-col gap-4">
            <div
              class="stats stats-vertical md:stats-horizontal shadow bg-base-100 w-full"
            >
              <div class="stat">
                <div class="stat-title">Version</div>
                <div class="stat-value text-xl">
                  {systemInfo?.version || "N/A"}
                </div>
              </div>
              <div class="stat">
                <div class="stat-title">UI Version</div>
                <div class="stat-value text-xl">{version}</div>
              </div>
            </div>
            <div
              class="stats stats-vertical md:stats-horizontal shadow bg-base-100 w-full"
            >
              <div class="stat">
                <div class="stat-title">Device Name</div>
                <div class="stat-value text-xl">
                  {systemInfo?.deviceName || "N/A"}
                </div>
              </div>
              <div class="stat">
                <div class="stat-title">Uptime</div>
                <div class="stat-value text-xl">
                  {systemInfo?.uptime || "N/A"}
                </div>
              </div>
              <div class="stat">
                <div class="stat-title">Free Heap</div>
                <div class="stat-value text-xl">
                  {systemInfo?.free_heap || "N/A"}
                </div>
              </div>
            </div>
            <div
              class="stats stats-vertical md:stats-horizontal shadow bg-base-100 w-full"
            >
              <div class="stat">
                <div class="stat-title">WiFi SSID</div>
                <div class="stat-value text-xl">
                  {systemInfo?.wifi_ssid || "N/A"}
                </div>
              </div>
              {#if !systemInfo?.eth_enabled}
                <div class="stat">
                  <div class="stat-title">WiFi RSSI</div>
                  <div class="stat-value text-xl">
                    {systemInfo?.wifi_rssi || "N/A"} ({wifi_signal})
                  </div>
                </div>
              {/if}
              <div class="stat">
                <div class="stat-title">Ethernet enabled</div>
                <div class="stat-value text-xl">
                  {systemInfo?.eth_enabled ? "Yes" : "No"}
                </div>
              </div>
            </div>
          </div>
        {/if}
      </div>
    </div>
  </div>
</div>
